### ISSUE TITLE
Throbber Reference

### ISSUE THREAD

**Issue by stompro** [mcoia/mobius_evergreen#2]
Hello, in the me_carousel.css, in the .jcarousel-item-placeholder section there is a background reference to a throbber.gif that doesn't exist, isn't included with your files.

I added a throbber.gif and changed the path so the file is found, but I cannot see that it ever shows up when I'm viewing it.  So it might make sense to just remove that reference.

Not a big deal, but since the main page gets loaded more than others, it would be nice to get rid of 404s.

**Comment by bmagic007** [comment]
Josh,

Thanks for the heads up. I removed that line. That CSS file is really a custom CSS for (ME) - Stands for Missouri Evergreen. Originally, I figured those that wanted the carousel code would adapt their own css for their institution.
